trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 'jefking/thebus'
    command: build
    Dockerfile: compute/Dockerfile