trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Docker@2
  displayName: 'container build & push'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'jefking/thebus'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'